import { IImpuchip } from "../types/types";

export const inputstabla: IImpuchip[] = [
  {
    id: 1,
    tipo: "number",
    name: "numero",
    label: "Numero:",
    valor: ["0"],
  },
  {
    id: 2,
    tipo: "number",
    name: "numerosim",
    label: "Numero SIM:",
    valor: ["0"],
  },
  {
    id: 3,
    tipo: "text",
    name: "puk",
    label: "PUK:",
    valor: ["0"],
  },
  {
    id: 4,
    tipo: "number",
    name: "sim",
    label: "SIM:",
    valor: ["0"],
  },
  {
    id: 5,
    tipo: "text",
    name: "cliente",
    label: "Cliente:",
    valor: ["0"],
  },
  {
    id: 6,
    tipo: "number",
    name: "numerodetelefono",
    label: "Numero de telefono:",
    valor: ["0"],
  },
  {
    id: 7,
    tipo: "date",
    name: "fechainicio",
    label: "Fecha inicio:",
    valor: ["0"],
  },
  {
    id: 8,
    tipo: "date",
    name: "vencimiento",
    label: "Vencimiento:",
    valor: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
  },
  {
    id: 9,
    tipo: "text",
    name: "correo",
    label: "Correo:",
    valor: ["0"],
  },
  {
    id: 10,
    tipo: "number",
    name: "valor",
    label: "Precio:",
    valor: ["0"],
  },
  {
    id: 11,
    tipo: "number",
    name: "Mg",
    label: "MG:",
    valor: ["0"],
  },
  {
    id: 12,
    tipo: "text",
    name: "empresa",
    label: "Empresa:",
    valor: ["0"],
  },
  {
    id: 12,
    tipo: "text",
    name: "marca",
    label: "Marca:",
    valor: ["0"],
  },
  {
    id: 12,
    tipo: "text",
    name: "patente",
    label: "Patente:",
    valor: ["0"],
  },
];
